// apps/frontend/src/lib/components/conference/committee/committee-seat-table.svelte
<script lang="ts">
  /**
   * committee-seat-table.svelte
   * ───────────────────────────
   * 席位表 —— 席位名称 / 简称 / 角色 / 访问 key，并就地提供
   * 复制 key、重新生成 key、编辑和删除席位等操作。
   * 依赖当前委员会已加载（席位操作均作用于当前委员会）。
   */
  import { onDestroy } from 'svelte'
  import { Check, Copy, Pencil, RefreshCw, Trash2, X } from '@lucide/svelte'
  import type { Seat, SeatAccess } from '$lib/classes/types/delegate'
  import {
    removeSeat,
    rotateSeatInviteCode,
    updateSeat
  } from '$lib/classes/stores/delegate/delegate-store'
  import { Button } from '$lib/components/ui/button'
  import { Input } from '$lib/components/ui/input'

  interface Props {
    seats: Seat[]
    /** 大会级访问记录，用于解析每个席位的邀请码 */
    seatAccesses?: SeatAccess[]
  }

  let { seats, seatAccesses = [] }: Props = $props()

  let copied = $state('')
  let editingSeatId = $state('')
  let editName = $state('')
  let editShortName = $state('')
  let deleteConfirmSeatId = $state('')
  let deleteConfirmTimer: ReturnType<typeof setTimeout> | undefined

  function inviteCode(seatId: string): string {
    return seatAccesses.find((access) => access.seatId === seatId)?.inviteCode ?? ''
  }

  async function copyCode(code: string, seatId: string): Promise<void> {
    if (!code) return
    await navigator.clipboard.writeText(code)
    copied = seatId
    setTimeout(() => copied === seatId && (copied = ''), 1400)
  }

  function startEditing(seat: Seat): void {
    clearDeleteConfirmation()
    editingSeatId = seat.id
    editName = seat.name
    editShortName = seat.shortName ?? ''
  }

  function cancelEditing(): void {
    editingSeatId = ''
    editName = ''
    editShortName = ''
  }

  function saveSeat(seat: Seat): void {
    const name = editName.trim()
    if (!name) return
    updateSeat(seat.id, { name, shortName: editShortName.trim() || undefined })
    cancelEditing()
  }

  function handleEditorKeydown(event: KeyboardEvent, seat: Seat): void {
    if (event.key === 'Enter') {
      event.preventDefault()
      saveSeat(seat)
    } else if (event.key === 'Escape') {
      event.preventDefault()
      cancelEditing()
    }
  }

  function clearDeleteConfirmation(): void {
    if (deleteConfirmTimer) clearTimeout(deleteConfirmTimer)
    deleteConfirmTimer = undefined
    deleteConfirmSeatId = ''
  }

  function handleDelete(seat: Seat): void {
    if (deleteConfirmSeatId !== seat.id) {
      clearDeleteConfirmation()
      deleteConfirmSeatId = seat.id
      deleteConfirmTimer = setTimeout(clearDeleteConfirmation, 3000)
      return
    }

    clearDeleteConfirmation()
    if (editingSeatId === seat.id) cancelEditing()
    removeSeat(seat.id)
  }

  onDestroy(clearDeleteConfirmation)
</script>

<div class="overflow-hidden rounded-lg border bg-card">
  <table class="w-full text-sm">
    <thead class="bg-muted/50 text-xs text-muted-foreground">
      <tr>
        <th class="px-4 py-3 text-left font-medium">席位</th>
        <th class="px-4 py-3 text-left font-medium">简称</th>
        <th class="px-4 py-3 text-left font-medium">角色</th>
        <th class="px-4 py-3 text-left font-medium">访问 key</th>
        <th class="px-4 py-3 text-right font-medium">操作</th>
      </tr>
    </thead>
    <tbody>
      {#each seats as seat (seat.id)}
        {@const code = inviteCode(seat.id)}
        <tr class="border-t">
          <td class="px-4 py-3 font-medium">
            {#if editingSeatId === seat.id}
              <Input
                bind:value={editName}
                aria-label="席位名称"
                onkeydown={(event) => handleEditorKeydown(event, seat)}
              />
            {:else}
              {seat.name}
            {/if}
          </td>
          <td class="px-4 py-3 font-medium">
            {#if editingSeatId === seat.id}
              <Input
                bind:value={editShortName}
                aria-label="席位简称"
                placeholder="可选"
                onkeydown={(event) => handleEditorKeydown(event, seat)}
              />
            {:else}
              {seat.shortName ?? '-'}
            {/if}
          </td>
          <td class="px-4 py-3 text-muted-foreground">{seat.role ?? '-'}</td>
          <td class="px-4 py-3"><code class="font-mono text-xs">{code || '未生成'}</code></td>
          <td class="px-4 py-3">
            <div class="flex justify-end gap-1">
              <Button
                variant="ghost"
                size="icon"
                title="复制 key"
                aria-label="复制 key"
                disabled={!code}
                onclick={() => void copyCode(code, seat.id)}
              >
                {#if copied === seat.id}<Check />{:else}<Copy />{/if}
              </Button>
              <Button
                variant="ghost"
                size="icon"
                title="重新生成 key"
                aria-label="重新生成 key"
                onclick={() => rotateSeatInviteCode(seat.id)}
              >
                <RefreshCw />
              </Button>
              {#if editingSeatId === seat.id}
                <Button
                  variant="ghost"
                  size="icon"
                  title="取消编辑"
                  aria-label="取消编辑"
                  onclick={cancelEditing}
                >
                  <X />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  title="保存席位"
                  aria-label="保存席位"
                  disabled={!editName.trim()}
                  onclick={() => saveSeat(seat)}
                >
                  <Check />
                </Button>
              {:else}
                <Button
                  variant="ghost"
                  size="icon"
                  title="编辑席位"
                  aria-label="编辑席位"
                  onclick={() => startEditing(seat)}
                >
                  <Pencil />
                </Button>
              {/if}
              <Button
                variant={deleteConfirmSeatId === seat.id ? 'destructive' : 'ghost'}
                size="sm"
                title="双击以删除席位"
                onclick={() => handleDelete(seat)}
              >
                <Trash2 data-icon="inline-start" />
                {#key deleteConfirmSeatId === seat.id}
                  删除
                {/key}
              </Button>
            </div>
          </td>
        </tr>
      {:else}
        <tr>
          <td colspan="5" class="px-4 py-10 text-center text-muted-foreground">暂无席位</td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// apps/platform/components/committee-seat-table.tsx
"use client"

import { useEffect, useRef, useState } from "react"
import type { JSX, KeyboardEvent } from "react"
import { Check, Copy, Pencil, Trash2, X } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import type {
  CommitteeType,
  RoleTemplateInput,
  SeatInput,
} from "@/lib/conference-client"
import {
  roleAllowedInCommittee,
  roleReference,
} from "@/lib/conference-structure"

const selectClassName =
  "h-9 w-full rounded-lg border border-input bg-background px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"

interface CommitteeSeatTableProps {
  seats: SeatInput[]
  roles: RoleTemplateInput[]
  committeeType: CommitteeType
  disabled?: boolean
  onChange: (seats: SeatInput[]) => void
}

function seatReference(seat: SeatInput, index: number): string {
  return seat.id ?? seat.clientId ?? String(index)
}

export function CommitteeSeatTable({
  seats,
  roles,
  committeeType,
  disabled = false,
  onChange,
}: CommitteeSeatTableProps): JSX.Element {
  const knownSeats = useRef(new Set(seats.map(seatReference)))
  const deleteTimer = useRef<ReturnType<typeof setTimeout>>(undefined)
  const copiedTimer = useRef<ReturnType<typeof setTimeout>>(undefined)
  const [copied, setCopied] = useState("")
  const [editing, setEditing] = useState("")
  const [editName, setEditName] = useState("")
  const [editShortName, setEditShortName] = useState("")
  const [editRole, setEditRole] = useState("")
  const [editVotingRights, setEditVotingRights] = useState(true)
  const [deleteConfirm, setDeleteConfirm] = useState("")

  const allowedRoles = roles.filter((role) =>
    roleAllowedInCommittee(role, committeeType)
  )

  function startEditing(seat: SeatInput, index: number): void {
    clearDeleteConfirmation()
    setEditing(seatReference(seat, index))
    setEditName(seat.name)
    setEditShortName(seat.shortName ?? "")
    setEditRole(seat.roleTemplateId)
    setEditVotingRights(seat.hasVotingRights)
  }

  function cancelEditing(): void {
    setEditing("")
    setEditName("")
    setEditShortName("")
    setEditRole("")
    setEditVotingRights(true)
  }

  function saveSeat(index: number): void {
    const name = editName.trim()
    if (!name || !editRole) return
    const next = [...seats]
    next[index] = {
      ...next[index],
      name,
      shortName: editShortName.trim() || undefined,
      roleTemplateId: editRole,
      hasVotingRights: editVotingRights,
    }
    onChange(next)
    cancelEditing()
  }

  function handleEditorKeyDown(
    event: KeyboardEvent<HTMLInputElement | HTMLSelectElement>,
    index: number
  ): void {
    if (event.key === "Enter") {
      event.preventDefault()
      saveSeat(index)
    } else if (event.key === "Escape") {
      event.preventDefault()
      cancelEditing()
    }
  }

  function clearDeleteConfirmation(): void {
    if (deleteTimer.current) clearTimeout(deleteTimer.current)
    deleteTimer.current = undefined
    setDeleteConfirm("")
  }

  function handleDelete(seat: SeatInput, index: number): void {
    const reference = seatReference(seat, index)
    if (deleteConfirm !== reference) {
      clearDeleteConfirmation()
      setDeleteConfirm(reference)
      deleteTimer.current = setTimeout(clearDeleteConfirmation, 3000)
      return
    }

    clearDeleteConfirmation()
    if (editing === reference) cancelEditing()
    onChange(seats.filter((_, seatIndex) => seatIndex !== index))
  }

  async function copyCode(code: string, reference: string): Promise<void> {
    if (!code) return
    await navigator.clipboard.writeText(code)
    if (copiedTimer.current) clearTimeout(copiedTimer.current)
    setCopied(reference)
    copiedTimer.current = setTimeout(() => setCopied(""), 1400)
  }

  useEffect(() => {
    const currentReferences = new Set(seats.map(seatReference))
    const addedIndex = seats.findIndex(
      (seat, index) =>
        !knownSeats.current.has(seatReference(seat, index)) && !seat.name.trim()
    )
    knownSeats.current = currentReferences
    if (addedIndex >= 0) startEditing(seats[addedIndex], addedIndex)
  }, [seats])

  useEffect(
    () => () => {
      if (deleteTimer.current) clearTimeout(deleteTimer.current)
      if (copiedTimer.current) clearTimeout(copiedTimer.current)
    },
    []
  )

  return (
    <div className="overflow-x-auto rounded-lg border bg-card">
      <table className="w-full text-sm">
        <thead className="bg-muted/50 text-xs text-muted-foreground">
          <tr>
            <th className="px-4 py-3 text-left font-medium">席位</th>
            <th className="px-4 py-3 text-left font-medium">简称</th>
            <th className="px-4 py-3 text-left font-medium">角色</th>
            <th className="px-4 py-3 text-left font-medium">投票权</th>
            <th className="px-4 py-3 text-left font-medium">访问 Key</th>
            <th className="px-4 py-3 text-center font-medium">操作</th>
          </tr>
        </thead>
        <tbody>
          {seats.map((seat, index) => {
            const reference = seatReference(seat, index)
            const isEditing = editing === reference
            const role = roles.find(
              (item) => roleReference(item) === seat.roleTemplateId
            )
            return (
              <tr key={reference} className="border-t align-middle">
                <td className="px-4 py-3 font-medium">
                  {isEditing ? (
                    <Input
                      value={editName}
                      disabled={disabled}
                      aria-label="席位名称"
                      onChange={(event) => setEditName(event.target.value)}
                      onKeyDown={(event) => handleEditorKeyDown(event, index)}
                    />
                  ) : (
                    seat.name || "未命名席位"
                  )}
                </td>
                <td className="px-4 py-3">
                  {isEditing ? (
                    <Input
                      value={editShortName}
                      disabled={disabled}
                      maxLength={32}
                      placeholder="可选"
                      aria-label="席位简称"
                      onChange={(event) => setEditShortName(event.target.value)}
                      onKeyDown={(event) => handleEditorKeyDown(event, index)}
                    />
                  ) : (
                    seat.shortName || "—"
                  )}
                </td>
                <td className="px-4 py-3 text-muted-foreground">
                  {isEditing ? (
                    <select
                      value={editRole}
                      disabled={disabled}
                      className={selectClassName}
                      aria-label="席位角色"
                      onChange={(event) => setEditRole(event.target.value)}
                      onKeyDown={(event) => handleEditorKeyDown(event, index)}
                    >
                      <option value="">选择角色</option>
                      {allowedRoles.map((allowedRole) => (
                        <option
                          key={roleReference(allowedRole)}
                          value={roleReference(allowedRole)}
                        >
                          {allowedRole.name || "未命名角色"}
                        </option>
                      ))}
                    </select>
                  ) : (
                    role?.name || "未选择"
                  )}
                </td>
                <td className="px-4 py-3">
                  {isEditing ? (
                    <label className="flex h-9 items-center gap-2 whitespace-nowrap">
                      <input
                        type="checkbox"
                        checked={editVotingRights}
                        disabled={disabled}
                        onChange={(event) =>
                          setEditVotingRights(event.target.checked)
                        }
                      />
                      有投票权
                    </label>
                  ) : seat.hasVotingRights ? (
                    "有"
                  ) : (
                    "无"
                  )}
                </td>
                <td className="px-4 py-3">
                  <code className="font-mono text-xs">
                    {seat.inviteCode || "未生成"}
                  </code>
                </td>
                <td className="px-4 py-3">
                  <div className="flex justify-end gap-1">
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      title="复制 Key"
                      aria-label="复制 Key"
                      disabled={disabled || !seat.inviteCode}
                      onClick={() =>
                        void copyCode(seat.inviteCode ?? "", reference)
                      }
                    >
                      {copied === reference ? (
                        <Check aria-hidden="true" />
                      ) : (
                        <Copy aria-hidden="true" />
                      )}
                    </Button>
                    {isEditing ? (
                      <>
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          title="取消编辑"
                          aria-label="取消编辑"
                          disabled={disabled}
                          onClick={cancelEditing}
                        >
                          <X aria-hidden="true" />
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          title="保存席位"
                          aria-label="保存席位"
                          disabled={disabled || !editName.trim() || !editRole}
                          onClick={() => saveSeat(index)}
                        >
                          <Check aria-hidden="true" />
                        </Button>
                      </>
                    ) : (
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        title="编辑席位"
                        aria-label="编辑席位"
                        disabled={disabled}
                        onClick={() => startEditing(seat, index)}
                      >
                        <Pencil aria-hidden="true" />
                      </Button>
                    )}
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      disabled={disabled}
                      className={
                        deleteConfirm === reference
                          ? "bg-destructive/10 text-destructive hover:bg-destructive/20 hover:text-destructive"
                          : undefined
                      }
                      title={
                        deleteConfirm === reference
                          ? "再次点击确认删除"
                          : "删除席位"
                      }
                      onClick={() => handleDelete(seat, index)}
                    >
                      <Trash2 aria-hidden="true" />
                      删除
                    </Button>
                  </div>
                </td>
              </tr>
            )
          })}
          {seats.length === 0 ? (
            <tr>
              <td
                colSpan={6}
                className="px-4 py-10 text-center text-muted-foreground"
              >
                暂无席位
              </td>
            </tr>
          ) : null}
        </tbody>
      </table>
    </div>
  )
}
